"""Build the H200 notebook for a separate, synthetic label-mapping LoRA."""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "notebooks/Cassava_H200_Qwen15B_Mapper_Training.ipynb"


def code(source: str):
    return nbf.v4.new_code_cell(source.strip())


def markdown(source: str):
    return nbf.v4.new_markdown_cell(source.strip())


def main() -> None:
    nb = nbf.v4.new_notebook()
    nb["metadata"]["kernelspec"] = {
        "display_name": "Python 3 (ipykernel)",
        "language": "python",
        "name": "python3",
    }
    nb["cells"] = [
        markdown(
            """
# Cassava H200 — separate Qwen1.5B label mapper

This notebook keeps the frozen diagnostic adapter untouched. It trains a
separate LoRA only to map a model-generated C1–C8 diagnosis to an arbitrary
displayed option label. Training examples are synthetic permutations derived
from **training conversations only**. Final answers are still generated by
Qwen inference.
"""
        ),
        code(
            r"""
from pathlib import Path
import copy, gc, json, random, re, time
import pandas as pd
import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig,
    Trainer, TrainingArguments,
)
from peft import (
    LoraConfig, get_peft_model, prepare_model_for_kbit_training,
)

PACKAGE = Path("/home/jovyan/frozen_local_15b_upload")
TRAIN_PATH = PACKAGE / "sft_data/train.jsonl"
VALID_PATH = PACKAGE / "sft_data/valid.jsonl"
DIAGNOSTIC_ADAPTER = Path("/home/jovyan/outputs/qwen25_15b_converted_from_mlx")
MAPPER_OUTPUT = Path("/home/jovyan/outputs/qwen25_15b_mapper_v1")
REPORT_DIR = Path("/home/jovyan/reports")
MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"
SEED = 42
MAX_LENGTH = 768

assert TRAIN_PATH.is_file()
assert VALID_PATH.is_file()
assert (DIAGNOSTIC_ADAPTER / "adapter_model.safetensors").is_file()
MAPPER_OUTPUT.mkdir(parents=True, exist_ok=True)
REPORT_DIR.mkdir(parents=True, exist_ok=True)

def read_jsonl(path):
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]

train_conversations = read_jsonl(TRAIN_PATH)
valid_conversations = read_jsonl(VALID_PATH)
assert len(train_conversations) == 5394
assert len(valid_conversations) == 864
print("Inputs verified:", len(train_conversations), len(valid_conversations))
"""
        ),
        code(
            r"""
CANONICAL = {
    "C1": "Excessive antenna downtilt causing weak coverage at the far cell edge.",
    "C2": "Overshooting coverage or serving distance greater than 1 kilometre.",
    "C3": "A neighboring cell offers better radio or throughput performance.",
    "C4": "Severe overlapping coverage from close non-colocated co-frequency cells.",
    "C5": "Frequent handovers or ping-pong mobility.",
    "C6": "PCI modulo-30 interference.",
    "C7": "High vehicle speed, typically above 40 kilometres per hour.",
    "C8": "Insufficient scheduled resource blocks, typically below 160 RBs.",
}
MAPPER_SYSTEM = (
    "Map the supplied semantic diagnosis to the offered choice whose description "
    "has the same meaning. Use only this prompt. Your entire response must be "
    "exactly one displayed label in the form \\boxed{LABEL}."
)
BLOCK_RE = re.compile(r"(Offered choices:\n)(.*?)(\n\nCondition results:)", re.S)
LINE_RE = re.compile(r"^-\s*(C[1-8])\s*:\s*(.+)$")
BOX_RE = re.compile(r"\\+boxed\{\s*([A-Za-z0-9]+)\s*\}", re.I)

description_sets = []
seen = set()
for record in train_conversations:
    text = record["messages"][1]["content"]
    match = BLOCK_RE.search(text)
    if not match:
        continue
    rows = []
    for line in match.group(2).splitlines():
        item = LINE_RE.match(line.strip())
        if item:
            rows.append((item.group(1), item.group(2)))
    if len(rows) == 8 and tuple(label for label, _ in rows) == tuple(CANONICAL):
        key = tuple(description for _, description in rows)
        if key not in seen:
            seen.add(key)
            description_sets.append(dict(rows))

assert description_sets, "No canonical training option descriptions found"
print("Unique training description sets:", len(description_sets))

label_families = [
    list("12345678"),
    list("ABCDEFGH"),
    [f"R{i}" for i in range(1, 9)],
    [f"X{i}" for i in range(1, 9)],
    [f"Z{i}" for i in range(1, 9)],
]

def mapping_prompt(semantic, choices):
    offered = "\n".join(f"- {label}: {description}" for label, description in choices)
    return (
        f"Semantic diagnosis: {semantic}\n"
        f"Meaning: {CANONICAL[semantic]}\n\n"
        f"Offered choices:\n{offered}\n\n"
        "Generate the displayed label whose description matches the semantic diagnosis."
    )

def build_mapper_rows(count, salt):
    rng = random.Random(f"{SEED}:{salt}")
    rows = []
    labels = list(CANONICAL)
    for index in range(count):
        semantic = labels[index % 8]
        descriptions = description_sets[index % len(description_sets)]
        displayed = list(label_families[index % len(label_families)])
        rng.shuffle(displayed)
        mapping = dict(zip(labels, displayed))
        choices = [(mapping[label], descriptions[label]) for label in labels]
        rng.shuffle(choices)
        rows.append({
            "messages": [
                {"role": "system", "content": MAPPER_SYSTEM},
                {"role": "user", "content": mapping_prompt(semantic, choices)},
                {"role": "assistant", "content": f"\\boxed{{{mapping[semantic]}}}"},
            ]
        })
    rng.shuffle(rows)
    return rows

mapper_train = build_mapper_rows(3200, "train")
mapper_valid = build_mapper_rows(320, "valid")
print("Synthetic mapper rows:", len(mapper_train), len(mapper_valid))
"""
        ),
        code(
            r"""
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
if tokenizer.pad_token_id is None:
    tokenizer.pad_token = tokenizer.eos_token

def encode(record):
    messages = record["messages"]
    prompt = tokenizer.apply_chat_template(
        messages[:-1], tokenize=False, add_generation_prompt=True
    )
    answer = messages[-1]["content"] + tokenizer.eos_token
    prompt_ids = tokenizer(prompt, add_special_tokens=False).input_ids
    answer_ids = tokenizer(answer, add_special_tokens=False).input_ids
    assert len(prompt_ids) + len(answer_ids) <= MAX_LENGTH
    return {
        "input_ids": prompt_ids + answer_ids,
        "attention_mask": [1] * (len(prompt_ids) + len(answer_ids)),
        "labels": [-100] * len(prompt_ids) + answer_ids,
    }

train_ds = Dataset.from_list(mapper_train).map(
    encode, remove_columns=["messages"], desc="Tokenizing mapper train"
)
valid_ds = Dataset.from_list(mapper_valid).map(
    encode, remove_columns=["messages"], desc="Tokenizing mapper validation"
)

class Collator:
    def __call__(self, features):
        width = max(len(item["input_ids"]) for item in features)
        ids, masks, labels = [], [], []
        for item in features:
            pad = width - len(item["input_ids"])
            ids.append(item["input_ids"] + [tokenizer.pad_token_id] * pad)
            masks.append(item["attention_mask"] + [0] * pad)
            labels.append(item["labels"] + [-100] * pad)
        return {
            "input_ids": torch.tensor(ids),
            "attention_mask": torch.tensor(masks),
            "labels": torch.tensor(labels),
        }

print("Datasets ready:", len(train_ds), len(valid_ds))
"""
        ),
        code(
            r"""
gc.collect()
torch.cuda.empty_cache()
quant = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
)
base = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=quant,
    device_map={"": 0},
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
)
base.config.use_cache = False
base = prepare_model_for_kbit_training(
    base, use_gradient_checkpointing=True
)
mapper_config = LoraConfig(
    r=8, lora_alpha=16, lora_dropout=0.05, bias="none",
    task_type="CAUSAL_LM",
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
)
model = get_peft_model(base, mapper_config, adapter_name="mapper")
model.print_trainable_parameters()

args = TrainingArguments(
    output_dir=str(MAPPER_OUTPUT),
    num_train_epochs=1.0,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=4,
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    optim="paged_adamw_8bit",
    bf16=True,
    tf32=True,
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=50,
    save_strategy="steps",
    save_steps=50,
    save_total_limit=2,
    report_to="none",
    remove_unused_columns=False,
    label_names=["labels"],
    seed=SEED,
    data_seed=SEED,
)
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=valid_ds,
    data_collator=Collator(),
)
print("Starting mapper training...", flush=True)
trainer.train()
mapper_final = MAPPER_OUTPUT / "final_adapter"
model.save_pretrained(str(mapper_final), selected_adapters=["mapper"])
tokenizer.save_pretrained(str(mapper_final))
print("Saved mapper:", mapper_final)
"""
        ),
        markdown(
            """
Stop after training and send Codex the final training/validation losses. The
next cell for combined diagnostic-plus-mapper evaluation will be supplied only
after the mapper adapter is safely saved.
"""
        ),
    ]
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, OUTPUT)
    print(OUTPUT)


if __name__ == "__main__":
    main()
